# Generated by Django 3.2.7 on 2021-12-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='fav',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/media/'),
        ),
    ]
